name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemS-Skade/buildozer-action@v1.2
        with:
          command: buildozer -v android debug
          subfolder: .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Kivy-App-APK
          path: bin/*.apk
